### ISSUE TITLE
Mainline kernel support

### ISSUE THREAD

**Issue by pali** [LairdCP/lrdmwl#2]
Hello! Do you have any plans to upstream this wifi driver into mainline linux kernel?

**Comment by dankephart** [comment]
Several years ago, the driver this was based on called mwlwifi was in the process of being upstreamed by Marvell: 
https://patchwork.kernel.org/patch/9482477/

Unfortunately, that was never fully completed. Our original plans were to upstream our additions to the driver after Marvell upstreamed mwlwifi. At the present moment, we don't have plans to upstream the driver by ourselves.
