### ISSUE TITLE
Consistent hang when stopping USB/USB driver

### ISSUE THREAD

**Issue by BiffaloBuff** [LairdCP/lrdmwl#3]
Hello,

I'm experiencing a hang on shutdown with the USB driver. By adding some instrumentation, I can see that the driver is hanging in the call to `tasklet_kill(&adapter->rx_task);` in `usb.c:mwl_usb_disconnect`. This hang happens when I'm using the card in AP mode, and occurs every time a card is stopped or removed.

This issue is blocking my project, so I'm willing to provide any additional required information.

## Environment

* lrdmwl 8.5.0.7
* using meta-laird-cp backports/firmware layer
* kernel 5.4.77 on armv7
* ST60-2230C-UU card

## Steps to Reproduce

1. Start `hostapd` to start the access point.
    a. Optional: stop `hostapd` to return the card to an idle state.
1. Trigger the hang by performing one of the following steps:
    a. Shutdown the system
    b. Unload the `lrdmwl_usb` module with `modprobe` or `rmmod`
    c. Trigger a radio reset using the `device_recovery` debugfs endpoint
    d. Physically unplug the USB card (if possible)
1. Observe the driver hangs (eg. modprobe and ksoftirq using 100% CPU, or the shutdown never completes)

If step 1 is omitted (the card is never actively brought up), the driver can be stopped/unloaded without issue.

## Other notes

Based on the hypothesis that the `rx_task` is not scheduled when `tasklet_kill` is called on it, I tried connecting a client to the access point and loading the link by running an iperf3 session across the interface. If I stop the driver using any of the above methods while iperf3 is running, the driver unloads cleanly. This suggests that the RX tasklet is indeed not scheduled when it is killed in the normal shutdown case.

I also tried to port the changes made to SDIO under bugs 14160 and 17096 to the USB driver. In `mwl_usb_disconnect` I re-enabled the RX tasklet if `priv->shutdown` was true; in the RX tasklet function I checked if `priv->shutdown` was set and if so, exited. These changes did resolve the hang, but lead to a crash the next time the driver is loaded. I'm still investigating this path.

**Comment by dankephart** [comment]
Thanks for the detailed information.  Please contact our support team and provide this information: https://www.lairdconnect.com/resources/support
